@startuml

title Modules

[Main] as main
[Parser] as parser
[Model] as model
[Registry] as registry
[<<rules.mcpd>>] as rules
[User\nInterface] as ui

main --> ui
main --> parser
ui --> model
ui --> registry
parser --> model
parser --> rules

@enduml
